name: Build

on:
  push:
    tags:
      - "*.*"

jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main

      - name: Build
        run: |
          Write-Verbose -Message "Script_${{ github.ref_name }}.zip" -Verbose

          New-Item -Path "Script_${{ github.ref_name }}" -ItemType Directory -Force

          Get-ChildItem -Path src -Force | Copy-Item -Destination "Script_${{ github.ref_name }}" -Recurse -Force

          $Parameters = @{
              Path             = "Script_${{ github.ref_name }}"
              DestinationPath  = "Script_${{ github.ref_name }}.zip"
              CompressionLevel = "Fastest"
              Force            = $true
          }
          Compress-Archive @Parameters

      - name: Uploading
        uses: softprops/action-gh-release@master
        with:
          name: ${{ env.RELEASE_NAME }}
          token: ${{ github.token }}
          files: Script_${{ github.ref_name }}.zip
